added or2 and infrastructure

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -1,4 +1,4 @@
-name: Setup
+name: Build
 
 on:
   push:
@@ -97,31 +97,61 @@ jobs:
               make install
               make veryclean
 
-      - name: Download Caravel
+      - name: LVS
         run: |
-              git clone --depth 1 https://github.com/efabless/caravel.git
-              make -C caravel gds/chip_io.gds
-
-      - name: Download Backend Layout Check Scripts
-        run: |
-              git clone --depth 1 https://github.com/d-m-bailey/extra_be_checks.git backend_layout_checks
-
-      - name: Verifiy Installation with Mitch Bailey's sky130_io Schematics
-        run: |
-              git clone --depth 1 https://github.com/d-m-bailey/sky130_fd_io.git mitch_bailey_sky130_io_schematics
-              cd mitch_bailey_sky130_io_schematics
-              export CARAVEL_ROOT=${{ github.workspace }}/caravel
-              export LVS_ROOT=${{ github.workspace }}/backend_layout_checks
-              export WORK_ROOT=${{ github.workspace }}/mitch_bailey_sky130_io_schematics/work/top_gpiov2
               export PDKPATH=${{ env.tools }}/open_pdks/share/pdk/sky130A
-              export PDK_ROOT=${{ env.tools }}/open_pdks/share/pdk
-              export PDK=sky130A
-              xschem --log test.log <<EOF
-                xschem load top_gpiov2.sch
-                set lvs_netlist 1
-                set netlist_dir [xschem get current_dirname]/simulation
-                xschem netlist
-                xschem exit closewindow force
-              EOF
-              grep "Symbol not found" test.log && exit 1 || echo "No Symbol Errors"
-              $LVS_ROOT/run_full_lvs lvs/top_gpiov2/lvs_config.json
+              make lvs/or2/sky130_fd_sc_hd__or2_0.report
+
+      - name: Generate SVGs
+        run: |
+              export PDKPATH=${{ env.tools }}/open_pdks/share/pdk/sky130A
+              make svg/or2/sky130_fd_sc_hd__or2_0.svg
+
+      - name: Tar
+        run: |
+          cd svg
+          tar -czf cells.tar.gz *
+
+      - name: Create Tag
+        run: |
+          echo "TAG_NAME=$(date +%Y.%m.%d.%H.%M)" >> "$GITHUB_ENV"
+          git tag ${{ env.TAG_NAME }}
+          git push origin ${{ env.TAG_NAME }}
+      - name: Create Release
+        uses: ncipollo/release-action@v1
+        with:
+          allowUpdates: True
+          omitBody: True
+          tag: ${{ env.TAG_NAME }}
+          artifacts: |
+            svg/cells.tar.gz
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      # - name: Download Caravel
+      #   run: |
+      #         git clone --depth 1 https://github.com/efabless/caravel.git
+      #         make -C caravel gds/chip_io.gds
+
+      # - name: Download Backend Layout Check Scripts
+      #   run: |
+      #         git clone --depth 1 https://github.com/d-m-bailey/extra_be_checks.git backend_layout_checks
+
+      # - name: Verifiy Installation with Mitch Bailey's sky130_io Schematics
+      #   run: |
+      #         git clone --depth 1 https://github.com/d-m-bailey/sky130_fd_io.git mitch_bailey_sky130_io_schematics
+      #         cd mitch_bailey_sky130_io_schematics
+      #         export CARAVEL_ROOT=${{ github.workspace }}/caravel
+      #         export LVS_ROOT=${{ github.workspace }}/backend_layout_checks
+      #         export WORK_ROOT=${{ github.workspace }}/mitch_bailey_sky130_io_schematics/work/top_gpiov2
+      #         export PDKPATH=${{ env.tools }}/open_pdks/share/pdk/sky130A
+      #         export PDK_ROOT=${{ env.tools }}/open_pdks/share/pdk
+      #         export PDK=sky130A
+      #         xschem --log test.log <<EOF
+      #           xschem load top_gpiov2.sch
+      #           set lvs_netlist 1
+      #           set netlist_dir [xschem get current_dirname]/simulation
+      #           xschem netlist
+      #           xschem exit closewindow force
+      #         EOF
+      #         grep "Symbol not found" test.log && exit 1 || echo "No Symbol Errors"
+      #         $LVS_ROOT/run_full_lvs lvs/top_gpiov2/lvs_config.json
