Update setup.yml

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -55,12 +55,13 @@ jobs:
               cd release
               ../configure --with-x --enable-xspice --disable-debug --enable-cider --with-readline=yes --enable-openmp --enable-osdi
               make
-      
-      - name: Install skywater-pdk Libraries     
-        run: |
-              git clone https://github.com/google/skywater-pdk.git
-              cd skywater-pdk
-              SUBMODULE_VERSION=latest make submodules -j3 || make submodules -j1
+
+      # # This code might not work? Seems there's a version difference :/
+      # - name: Install skywater-pdk Libraries     
+      #   run: |
+      #         git clone https://github.com/google/skywater-pdk.git
+      #         cd skywater-pdk
+      #         SUBMODULE_VERSION=latest make submodules -j3 || make submodules -j1
 
       # Unclear if PDK files generated
       - name: Generate PDK files
@@ -68,27 +69,28 @@ jobs:
               git clone --depth 1 git://opencircuitdesign.com/open_pdks
               cd open_pdks
               echo "$GITHUB_WORKSPACE/open_pdks" >> $GITHUB_PATH
-              ./configure --prefix=${{ github.workspace }}/open_pdks
+              ./configure --prefix=${{ github.workspace }}/open_pdks --enable-sky130-pdk --enable-sram-sky130
               make
               sudo make install
               make veryclean
-      # # Always exit 1, idk why. Seems to open properly but I think it doesn't like displaying the GUI, causing exit 1
-      # - name: Verify Installation
-      #   run: |
-      #         git clone --depth 1 https://github.com/d-m-bailey/sky130_fd_io.git
-      #         cd sky130_fd_io
-      #         export PDKPATH=${{ github.workspace }}/open_pdks
-      #         xschem --log test.log <<EOF
-      #         xschem load f sky130_fd_io/top_gpiov2.sch 
-      #         xschem exit closewindow force
-      #         EOF
-      #         if grep -q "Symbol not found" test.log; then
-      #           echo "Error: Symbol not Found"
-      #           exit 1
-      #         else
-      #           echo "No Symbol Errors"
-      #           exit 0
-      #         fi
+              
+      # Always exit 1, idk why. Seems to open properly but I think it doesn't like displaying the GUI, causing exit 1
+      - name: Verify Installation
+        run: |
+              git clone --depth 1 https://github.com/d-m-bailey/sky130_fd_io.git
+              cd sky130_fd_io
+              export PDKPATH=${{ github.workspace }}/open_pdks
+              xschem --log test.log <<EOF
+              xschem load f sky130_fd_io/top_gpiov2.sch 
+              xschem exit closewindow force
+              EOF
+              if grep -q "Symbol not found" test.log; then
+                echo "Error: Symbol not Found"
+                exit 1
+              else
+                echo "No Symbol Errors"
+                exit 0
+              fi
               
       - name: Install caravel
         run: |
